

POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
    "firstName": "Rubel",
    "lastName": "Hossain",
    "email":"rubel@gmail.com",
    "password": "Password123!",
    "phone": "1234567890"
}
###
POST  http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"rubel@gmail.com",
    "password": "Password123!"
}
###
GET http://localhost:3000/api/v1/users

###
GET  http://localhost:3000/api/v1/rbac/roles

###
POST  http://localhost:3000/api/v1/rbac/roles
Content-Type: application/json

{
    "name": "Admin"
}
###
POST  http://localhost:3000/api/v1/rbac/permissions
Content-Type: application/json

{
    "name": "create-user",
    "resource": "user",
    "action": "create"
}
###
POST  http://localhost:3000/api/v1/rbac/user-roles
Content-Type: application/json

{
    "userId": "user-uuid-here",
    "roleId": "role-uuid-here",
    "assignedById": "admin-uuid-here"
}
###
DELETE  http://localhost:3000/api/v1/rbac/user-roles/user-uuid-here/role-uuid-here

###
GET  http://localhost:3000/api/v1/rbac/user-permissions/user-uuid-here

###
POST http://localhost:3000/api/v1/auth/forgot-password
Content-Type: application/json

{
    "email": "arfan@yopmail.com"
}

###
POST http://localhost:3000/api/v1/auth/reset-password
Content-Type: application/json

{
    "token": "PASTE_RESET_TOKEN_HERE",
    "newPassword": "newPassword123"
}